version: '3.8'
services:
  koala-attachment-handler:
    image: koala-attachment-handler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development